apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
  labels:
    app: was
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: rnjstngks/side-project-was:20
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: was-service
spec:
  type: ClusterIP
  clusterIP: 10.233.0.2
  selector:
    app: was
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080