name: Step-2

on: 
    push:
        branches:
            - main
        paths:
            - "Step-2/sbb/src/main/resources/templates/*.html"
            - "Step-2/sbb/build.gradle"
            - "Step-2/sbb/src/main/java/com/example/demo/answer/*"
            - "Step-2/sbb/src/main/java/com/example/demo/question/*"
            - "Step-2/sbb/src/main/java/com/example/demo/user/*"
            - "Step-2/sbb/src/main/java/com/example/demo/*"

jobs:
    gradle:
        runs-on: self-hosted 
        
        steps:
            - name: checkout sources
              uses: actions/checkout@v4
        
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
        
            - name: Build with Gradle
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-2/sbb
              run: ./gradlew build --stacktrace --info
            
            - name: Copy jar file
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-2/sbb/build/libs
              run: cp *-SNAPSHOT.jar /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-3/

            - name: Push jar file
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-3/
              run: |
                git config --global user.name "rnjstngks"
                git config --global user.email "rnjstngks267@naver.com"
                git add *.jar
                git commit -m "Upload jar file"
                git push origin main