name: Step-3

on: 
    push:
        branches:
            - main
        paths:
            - "Step-2/sbb/src/main/resources/templates/*.html"
            - "Step-2/sbb/build.gradle"
            - "Step-2/sbb/src/main/java/com/example/demo/answer/*"
            - "Step-2/sbb/src/main/java/com/example/demo/question/*"
            - "Step-2/sbb/src/main/java/com/example/demo/user/*"
            - "Step-2/sbb/src/main/java/com/example/demo/*"

jobs:
    gradle_build:
        runs-on: self-hosted 
        
        steps:
            - name: checkout sources
              uses: actions/checkout@v4
        
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
        
            - name: Build with Gradle
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-2/sbb
              run: ./gradlew build --stacktrace --info
            
            - name: Copy jar file
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-2/sbb/build/libs
              run: cp *-SNAPSHOT.jar /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-3/was/

            - name: Push jar file
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-3/was/
              run: |
                git config --global user.name "github-action[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add *.jar
                git commit -m "Upload jar file"
                git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/rnjstngks/Side-Project.git main
    
    Docker_image_build:
        runs-on: self-hosted

        steps:
            - name: checkout sources
              uses: actions/checkout@v4
              
            - name: Docker Build
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-3/was/
              run: docker build -t rnjstngks/side-project:${{ github.run_number }} .
          
            - name: Docker Hub login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
              
            - name: Docker Push
              run: docker push rnjstngks/side-project:${{ github.run_number }}

    Change_YAML_file:
        runs-on: self-hosted

        steps:
            - name: Push jar file
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-3/was/
              run: |
                git config --global user.name "github-action[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add *.jar
                git commit -m "Upload jar file"
                git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/rnjstngks/Side-Project.git main