name: Step-1

on: 
    push:
        branches:
            - main
        paths:
            - "Step-1/ansible/*"
            - "Step-1/ansible/roles/master/tasks/*"
            - "Step-1/ansible/roles/package/tasks/*"
            - "Step-1/terraform/*.tf"
jobs:
    terraform:
        runs-on: self-hosted # 내 Window 환경에서 Terraform 실행
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
        
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.10.1
        
            - name: Terraform Init
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-1/terraform
              run: |
                set -e
                terraform init
        
            - name: Terraform Apply
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-1/terraform
              run: |
                set -e
                terraform apply -auto-approve
        
            - name: Wait for VM to initialize
              run: sleep 120
    
    ansible:
        needs: terraform # terraform job 완료 후 실행
        runs-on: self-hosted # 내 Window 환경에서 Terraform 실행
        
        steps:       
            - name: Install sshpass Package
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-1/ansible
              run: ansible-playbook -vvv -i inventory.ini setup.yml --tags "package"

            - name: Install k8s Cluster (Used kubespray)
              working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/Side-Project/Step-1/ansible
              run: ansible-playbook -vvv -i inventory.ini setup.yml --tags "master"